### PR TITLE
configure nsswitch.conf to use systemd-resolved

### PR DESCRIPTION
**Pull request by hollow**
as per https://www.freedesktop.org/software/systemd/man/nss-resolve.html

### CODE REVIEW

**Comment by aruhier** [comment]
Thanks for the PR, but I think that the nsswitch.conf needs to be a bit more variable. At least the host section.

Also, I would probably allow to not configure the nsswitch.conf at all, through a variable like a did to enable or not resolved.

**Comment by hollow** [comment]
@aruhier I agree and for good measure I have converted all nsswitch directives to variables :)

**Comment by aruhier** [comment]
That's great, thanks a lot!
Sorry to be picky about it, but can you also add that in the README? I wouldn't expect this role to touch to nsswitch.conf, so adding that and how to disable this feature if needed would be great.

Thanks!

**Comment by aruhier** [comment]
Thanks a lot for this PR, LGTM!

**Pull request merged**
